### ISSUE TITLE
Add suport for customizing the class name

### ISSUE THREAD

**Issue by markky21** [renatomoor/storybook-tailwind-dark-mode#12]
Please add support for customizing the class name accordingly to [Tailwind docs](https://tailwindcss.com/docs/dark-mode#customizing-the-class-name)

**Comment by renatomoor** [comment]
@freddyamarante can you look at this?

Seems easy to do with the global variable.

**Comment by freddyamarante** [comment]
@markky21 already merged the solution, take a look
