### ISSUE TITLE
Storybook 7 - docs-root does not exists to add `dark` class

### ISSUE THREAD

**Issue by adityapant1286** [renatomoor/storybook-tailwind-dark-mode#14]
Hi @renatomoor,

Thank you for your efforts working on this package.

There is an error observed for Storybook 7. The element to add `dark` class is null as there is no such element exists with the id `docs-root`. This errors out when adding `dark` class.
Changing the background of `body` element is working, but this is a hack. Please advise.

- Storybook 7
- React 18
- storybook-tailwind-dark-mode 1.0.16

https://github.com/renatomoor/storybook-tailwind-dark-mode/blob/2860d303f524a617ac8bf0a87dd31bc974b8dbcd/src/withGlobals.js#L9

Receiving this error for Docs:

![image](https://user-images.githubusercontent.com/13958935/230129718-835900eb-6c31-4b41-bf59-8edfcfcee7e8.png)

**Comment by JReinhold** [comment]
@renatomoor the element that had the id `docs-root` in 6.5, now has the id `storybook-docs` in 7.0. You could try changing the implementation to that and see if it fixes it. However I would expect it to be a breaking change to this addon, since it would make it only compatible with 7.0, but that's not for me to decide.

The change can be seen here https://github.com/storybookjs/storybook/pull/10638

**Comment by renatomoor** [comment]
@JReinhold @adityapant1286.

@freddyamarante has made the fix and has also released the new version

**Comment by adityapant1286** [comment]
Hi @freddyamarante , thank you for fixing it. Not sure it is an issue with storybook 7 or this case is failing.

The controls are showing correct colors for dark and light mode. However, the background color remains white.

Button in light-mode

![image](https://user-images.githubusercontent.com/13958935/233791970-167c6bea-ffc2-41c3-9c41-d7cba08305ca.png)


Button in dark-mode

![image](https://user-images.githubusercontent.com/13958935/233792010-95222242-c3f9-46e5-bc41-f3d5b9649267.png)

Perhaps need to update background color of the body element having `.sb-show-main` class.

![image](https://user-images.githubusercontent.com/13958935/233792153-78528e8f-3856-46f3-9403-fba4efbe997e.png)

preview.ts file for a reference
```
const preview: Preview = {
  globalTypes: {
    darkMode: {
      defaultValue: true, // Enable dark mode by default on all stories
    }
  },
  parameters: {
    actions: { argTypesRegex: "^on[A-Z].*" },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/,
      },
    },
    darkMode: {
      current: 'light',
      dark: { ...themes.dark, appBg: '#171717' },
      light: { ...themes.normal, appBg: '#ffffff' }
    },
  },
};

```

**Comment by freddyamarante** [comment]
I'll take a look at it! I also think would be convenient to add a way to input what background color you want, I'll pr soon

**Comment by adityapant1286** [comment]
Hi @renatomoor and @freddyamarante, this recent request is closed, would you advise moving to a new issue or mark this to 'open'.
