### ISSUE TITLE
Does this work with dark: "media" in a tailwind.config.js?

### ISSUE THREAD

**Issue by Julianwan** [renatomoor/storybook-tailwind-dark-mode#2]
I can't seem to use this no matter how many ways I fiddle with it.

I'm using a mono-repo and need to use media preference for dark / light mode, and this addons seems to just... not work.

**Comment by jayaramkasi** [comment]
@Julianwan This seems to work for me. 

Have you checked if `<div id="root">` is getting a class of "dark"?

**Comment by renatomoor** [comment]
@Julianwan I see the problem,
but if I'm right, you should not need a plugin if you are using the media mode of tailwind
as, the dark mode should be toggled automatically with your device preference.

If you want to use this plugin, you should have this in your `tailwind.config.js`
```
module.exports = {
  darkMode: 'class',
  // ...
}
```

**Comment by Julianwan** [comment]
@renatomoor thank you.

My situation is unique. It's a monorepo using Next.js to host a static site, and building stories alongside my components.

The site itself uses media class, but I have been trying to get storybook to use native "class" based theme, for design and quality assurance purposes.

I can always toggle my system settings but it's not easy to explain how to do that for other team members, so I wanted a native toggle within the storybook ui.

**Comment by razzeee** [comment]
That you need to have it in class mode, should probably be mentioned in the readme. Would have saved me time, as that's not the default (anymore?)
