### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by jayaramkasi** [renatomoor/storybook-tailwind-dark-mode#3]
First up, Great work, @renatomoor with this addon.
 
Please Add the following to the readme. I found this by reading your code, it might be helpful for someone else using it.

"
### Dark Mode as default

If you want the storybook to have dark mode as default, add the following lines to ./storybook/preview.js
`
export const globalTypes = {
  darkMode: true,
};
`
"

**Comment by jayaramkasi** [comment]
Have put a PR https://github.com/renatomoor/storybook-tailwind-dark-mode/pull/4

**Comment by renatomoor** [comment]
Thanks, @jayaramkasi! Your PR is merged!
